### ISSUE TITLE
Strange broadening with bright Bragg peaks

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#108]
I've found that when broadening S(Q,w) data that contains data with very bright Bragg peaks (~10 orders of magnitude brighter than the rest of the data) the plots produced are very strange, seen below for LZO and Nb:

![image](https://user-images.githubusercontent.com/18187336/99651981-2cf57980-2a4f-11eb-9842-5462333be221.png)
![image](https://user-images.githubusercontent.com/18187336/99652020-367ee180-2a4f-11eb-8f56-949ac0c4c3fb.png)

Similar behavour is seen with both 'gauss' and 'lorentz' broadening. It should be investigated to see whether this is unavoidable or a result of the broadening method used.

**Comment by ajjackson** [comment]
I think I understand what is happening. This is only seen when extreme amounts of clipping is applied to the data (~ 5 orders of magnitude or more!) by setting `vmax` in order to visualise the fainter plot lines. This raises the noise floor of the FFT convolution from imperceptible levels to something more dramatic. I suspect the problem will also be reduced by using more bins, as the precision of the FFT representation of the signal is directly related to the sampling frequency.

Solutions include:
- perform the broadening in realspace, so that precision depends on our float datatype. It's all addition and multiplication so should hold up well over a wide data range. (I think this is the approach you went for? `scipy.signal.oaconvolve` should be a drop-in replacement that works efficiently with these small broadening kernels.)
- apply clipping _before_ broadening so that the noise floor is consistent across the visible data. The problem is that we are then no longer simply passing `vmax` to Matplotlib, so there become two ways of doing things - more mess.
- somehow transform the space to e.g. logarithmic and apply the broadening there. Haven't really worked out if that's actually possible, may need to modify the kernels. Let's not do that.

**Comment by ajjackson** [comment]
Have had a little play and the implementation in #109 seems to have a performance penalty compared to the existing implementation. `oaconvolve` doesn't make any difference, and `signal.convolve(method='direct')` has worse performance while also solving the problem.

![euphonic-convolution-options](https://user-images.githubusercontent.com/2511383/99959806-8fb68000-2d83-11eb-8a4c-46819ec7b8e2.png)
