### ISSUE TITLE
Libopenblas*dll not found on Windows via Conda

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#147]
Running:
```
conda create -n py37 python=3.7
conda install numpy scipy euphonic
```
Then trying to use the C extension results in:
```
RuntimeError: Could not load zheevd function
Could not find C:\tools\miniconda3\envs\py37\lib\site-packages\scipy\..\numpy\.libs\libopenblas*dll
```

User reports there is a libopenblas*dll in `C:\tools\miniconda3\envs\py37\Lib\site-packages\scipy\.libs\`

**Comment by ajjackson** [comment]
Is the numpy getting installed from conda-forge? I'm surprised conda found euphonic without a `-c conda-forge`, maybe it was somehow added globally in your miniconda setup?

**Comment by mducle** [comment]
sorry I mistyped in the chat. It should be:

```
conda create -n py37 python=3.7
conda activate py37
conda install -c conda-forge euphonic
```

Then run a simple script, e.g.

```python
import seekpath
import numpy as np
from euphonic import ForceConstants

# Read quartz data from quartz.castep_bin
filename = 'quartz/quartz.castep_bin'
fc = ForceConstants.from_castep(filename)

# Generate a recommended q-point path using seekpath
cell = fc.crystal.to_spglib_cell()
qpts = seekpath.get_explicit_k_path(cell)["explicit_kpoints_rel"]

# Calculate frequencies/eigenvectors
phonons = fc.calculate_qpoint_phonon_modes(qpts, asr='reciprocal')
```

(from the docs)

I get the error:

```
Could not find C:\tools\miniconda3\envs\py37b\lib\site-packages\scipy\..\numpy\.libs\libopenblas*dll
Could not find C:\tools\miniconda3\envs\py37b\lib\site-packages\scipy\..\numpy\.libs\libopenblas*dll
Traceback (most recent call last):
  File ".\euphonic_tutorial.py", line 14, in <module>
    phonons = fc.calculate_qpoint_phonon_modes(qpts, asr='reciprocal')
  File "C:\tools\miniconda3\envs\py37b\lib\site-packages\euphonic\force_constants.py", line 341, in calculate_qpoint_phonon_modes
    return_eigenvectors=True)
  File "C:\tools\miniconda3\envs\py37b\lib\site-packages\euphonic\force_constants.py", line 615, in _calculate_phonons_at_qpts
    scipy.__path__[0])
RuntimeError: Could not load zheevd function
```

**Comment by mducle** [comment]
Ok... There seems to be several cases I can see.

1. `pip install numpy` - `libopenblas*.dll` is in the `numpy/.libs` folder
2. `conda install numpy; pip install scipy` - `libopenblas*.dll` is in the `scipy/.libs` folder
3. `conda install [scipy|numpy]` - `libopenblas*.dll` not installed, but `mkl_*dll` are installed.
4. `conda install -c conda-forge [scipy|numpy]` - `libopenblas*.dll` not installed but `liblapack.dll` is installed.

Now, the cool thing is that both `mkl_*.1.dll` and `liblapack.dll` are on the system path and can be loaded with a straight `lib = LoadLibrary("liblapack.dll")` since Windows will search the system path for you.

`liblapack.dll` provides a standard interface so we can use the code as is. `mkl*dll` however have their own functions - `mkl_lapack_zheevd` with a different signature...
