### ISSUE TITLE
Python type-hinting

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#165]
Raised by @DBJochym in a meeting: we are currently using Python's type-hinting in the Euphonic code-base, but not entirely consistently. It would be helpful to document the project's attitude towards this and outline a policy for contributed code if appropriate.

My current thoughts on this are that while type-hinting is an expressive way of writing and documenting Python functions, the static analysis tool Mypy does not work very usefully with Numpy arrays and Pint quantities. As these constitute a significant fraction of the data passed around Euphonic, I would be reluctant to impose an "all code should be annotated" or "mypy must pass" policy. But maybe if we think about this a little more there is another useful policy we can consider. At the very least we should mention our preferences in CONTRIBUTING.

@rebeccafair

**Comment by rebeccafair** [comment]
Just updating some of the things we've touched on in other discussions here.

The generic use of `Quantity` and `np.ndarray` for typing is not ideal as it omits shape, type (float/int) and units information, but there are signs from the pint developers this may improve in the future in Pint issues 778, 1166 and currently there is a Pint PR in progress 1259. This would probably require bumping the versions of Pint/Numpy we depend on, but maybe Mantid's version restrictions will also have moved on by then so it might not be an issue. For now we should continue using `Quantity` and `np.ndarray` and putting shape, type and unit info in the docstring.

One other issue is that we currently have a bit of inconsistency in our use of `TypeVar`. `QpointFrequencies` and `QpointPhononmodes` use a generic `T` symbol to indicate 'whatever this class is', which works when subclassing because you get a generic `T` in the docs, rather than something contradictory. Whereas `Spectrum`, `Spectrum1D` etc. use `S`, `S1D` which means that in the `Spectrum1D` subclass you get a mix of `S` and `S1D` depending on which methods are inherited, which is a bit confusing. I would propose to move everything to use a generic `T` to avoid this.

In any case, Euphonic should be updated so all classes/methods/functions handle typing consistently, which would be an improvement, as currently some functions have no typing at all.

Whether we impose any hard restrictions on linting/type checking and what tools we'll use should maybe be another discussion. There are some brief Euphonic style guidelines here which could be added to https://github.com/pace-neutrons/pace-developers/blob/master/euphonic/development/03_style_guidelines.md.
