### ISSUE TITLE
Plotting customisation

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#185]
I think I mentioned this previously but can't find an issue for it; we should provide a way for command-line users to customise the fonts, figure size, subplot spacing, tick styles etc. for publication-quality plots. Matplotlib provides a format for this: [matplotlibrc file](https://matplotlib.org/stable/tutorials/introductory/customizing.html#customizing-with-matplotlibrc-files).

In [sumo](https://github.com/smtg-ucl/sumo) we make good use of matplotlib's cascading style system. Euphonic's default plots are bare-bones enough that we probably don't need to worry about that too much, but if we provide an argument that accepts inbuilt styles and matplotlibrc files then we don't have to add 100 different options for fine details in the order people request them.

As I'd like to make some publication-ready plots now I'll try hacking a Euphonic branch to support this and see how complex it gets. Are there any other problems I should consider? Or options that really should be settable from CLI without writing a config file?

**Comment by mducle** [comment]
I guess you're talking about the commandline tools? (Since using Euphonic in a Python script you can use the rc-file or `matplotlib.style` (thanks for pointing this out - I didn't know about this feature before!).

If so, then I think basic things like font sizes, marker sizes and linewidths should be modifiable on the command line - hopefully that should not proliferate the options too much... (You can maybe just have a single font size which sets the axes label and title size and the tick labels would be automatically 2 pt smaller or something).

**Comment by ajjackson** [comment]
Right, my experience with Sumo has been that

- these things proliferate quite quickly and do add complexity to the code
- end-users really appreciate them

so while a seemingly "small thing" some care is needed.

**Comment by ajjackson** [comment]
> (You can maybe just have a single font size which sets the axes label and title size and the tick labels would be automatically 2 pt smaller or something).

Good news: Matplotlib already has this built in; font sizes can be specified as small/medium/large/etc relative to `font.size` :smile:
