### ISSUE TITLE
calculate_sqw_map doesn't handle discontinuities elegantly

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#84]
I was trying to plot some neutron-weighted band structures using euphonic. My script is here: https://gist.github.com/ajjackson/21362eb4db1b7dcdb91371c4b6fab9d7

The results look quite good until we hit the non-continuous "extra" branches at the right-hand side. With `calculate_sqw_map` labelling the special points, they get spread out:

![defaults](https://user-images.githubusercontent.com/2511383/89201906-18799800-d5aa-11ea-983a-730b8e7214bb.png)

With some custom code to override the labelling, we can bring the _labels_ together...

![custom_pts](https://user-images.githubusercontent.com/2511383/89201934-23342d00-d5aa-11ea-9f74-eb4689601f1a.png)

but on the plot we still have horizontal artefacts. The discontinuity interacts with a binning/pixellation scheme to gives an overly generous amount of x-axis space to these points. For reference, the phonon band structure plot: http://phonondb.mtl.kyoto-u.ac.jp/ph20180417/d000/mp-661.html

So, the question is what next? The existing setup makes a lot of sense for extended-zone-scheme cuts through the structure. Perhaps it should not change. But these Brillouin-zone plots are very useful. Perhaps a different `calculate_sqw_map` mode/implementation should return multiple Spectrum2D objects that have been separated at the appropriate points?

**Comment by rebeccafair** [comment]
This is a fair point, I'd always intended to handle discontinuities similarly to in the bandstructures by putting them on a separate subplot, but never got round to it.

I do like the idea of `calculate_sqw_map` returning multiple `Spectrum2D` objects on discontinuities, maybe we can set a default 'break tolerance' argument like in `plot_dispersion` (if users still want everything in one object they can set a high tolerance), and then allow `plot_2d` to take a list of `Spectrum2D` objects.

**Comment by ajjackson** [comment]
Detecting discontinuities is an operation that could always be a bit fragile. Given that the user already knows where the discontinuities are, maybe we should just require them to use that information!

The underlying trouble here is that conventional band structure plots actually have k-point data that is 3 levels deep: 
```python
[[[k1a, k1b, k1c], [k2a, k2b, k2c], ...], # branch 1
 [[k11a, k11b, k11c], [k12a, k12b, k12c]], # branch 2
 ...]
```

while our objects in Euphonic work with a 2-D array of k-points without branch divisions.

So the options I see are:
1. Support multiple k-point branches all the way through Euphonic
2. Work with a single k-point array until `calculate_sqw_map`, then re-split the data to multiple Spectrum2D objects.
3. _Only_ support 2-D k-point arrays, process each branch separately and bring them together only at plotting time.

(1) increases the complexity of most of the codebase for the sake of a few conveniences; this looks unacceptable.

(2) and (3) have a common challenge in that we need to somehow capture and pass around information about the relative x-axis sizes of the branches for correct plotting. We can manage this "for free" by having the x-axis coordinates in meaningful units of reciprocal distance that can be inspected and manipulated. We just need to ensure that the multi-2d-plotter makes use of this information; the `width_ratios` option in _gridspec_ looks like the right way to do this.

(2) has the problem of how to implement splitting; some kind of arbitrary threshold would be used (but this is ok to work with in practice?)

(3) keeps the core elements of Euphonic as simple as possible, and imposes slightly more complexity on a plotting program. I think that is also manageable, especially if we provide a useful sample program in _scripts_.

I propose to initially work on (3) by
- modifying plot_2d to accept an `ax` argument
- writing a new `plot_2d_multi` that accepts multiple Spectrum2D axes and uses their x-coordinate ranges to gridspec them nicely to a new figure
- writing a script that reads a ForceConstants JSON, gets a standard bandpath using ASE (or seekpath?) and outputs a nice spectral dispersion plot.

**Comment by rebeccafair** [comment]
I agree that (2) and (3) are the only realistic options. I feel like (2) would be a useful option to keep parity with `plot_dispersion`, but this could be implemented later.

Just a few comments/questions:
* I'm not sure I understand what `ax` is used for?  What information is needed that isn't in the Spectrum2D object?
* `plot_1d` already accepts either a `Spectrum1D` object or a list of them, we should probably have the same for `plot_2d`, rather than having the user call another function `plot_2d_multi`
* An example script is a good idea, I'd prefer to use seekpath rather than ASE as that's what's already been used in the examples but it doesn't matter too much. We should think of somewhere to put these example scripts (as opposed to 'utility' scripts like `dispersion/dos.py`) and they should probably be tested too. It might make sense to put them in the `tutorials` directory, but the things in there are currently in the form of Jupyter notebooks and should probably be converted to scripts.

**Comment by ajjackson** [comment]
- `ax` is used to specify where the output is plotted. At the moment `plot_2d` is hard to reuse because it insists on creating a new figure. An alternative approach would be to strip back `plot_2d` to something more minimal and put the other stuff in a new `pretty_plot_2d`.

- Adding `ax` to `plot_2d` would create a problem with accepting a list of Spectrum2D. What happens if you use both features? Raise an error? Plot all of them on the same axis? Plot the first one on the specified axis and then go hunting for others? Probably best to raise an error.

- I thought this one would be ok in _scripts_ because it's generally useful, not redundant and would have a nice Argparse interface.

**Comment by ajjackson** [comment]
Also: I'm not keen on the way plot_2d plots each q-bin individually and returns a list of (potentially thousands of) AxesImage. If I "fix" the plotting to use a single NonUniformImage, this return value will change. Is that going to break anything?

Actually, the return value is also an issue with providing an `ax` option; it no longer makes sense to return a Figure. But I guess it _can_ return the Figure that `ax` was attached to.

**Comment by rebeccafair** [comment]
Ah, I see the issue now! How about we go the other way, and instead of having `plot_2d_multi` we have `plot_2d_single` (maybe it should be `_plot_2d_single`? Not sure) which accepts an `ax` argument? I feel like having `plot_1d/2d` as the 'standard' plot that people would call most of the time is best as its easy to remember, then if users want to do anything fancy they can call the lower level `plot_2d_single` etc.

Sorry I also misunderstood what you meant by writing a script, if it's nicely written with an argparse interface it definitely belongs in `scripts`!

**Comment by rebeccafair** [comment]
> Also: I'm not keen on the way plot_2d plots each q-bin individually and returns a list of (potentially thousands of) AxesImage. If I "fix" the plotting to use a single NonUniformImage, this return value will change. Is that going to break anything?
> 
> Actually, the return value is also an issue with providing an `ax` option; it no longer makes sense to return a Figure. But I guess it _can_ return the Figure that `ax` was attached to.

I agree returning many AxesImages isn't the best, I'd be happy for this to be fixed! As far as I know no other code depends on this (apart from maybe one of the example scripts, and the documentation would have to be updated to reflect this).

We could have `plot_2d` still returning a figure, and `plot_2d_single` just modifies the given `ax` rather than returning anything?

**Comment by ajjackson** [comment]
I'll start with something like `_plot_2d_core(Spectrum2D, ax)` but I don't see why it wouldn't be part of the user API once we come up with a better name :smile: 

I'm not keen on `plot_2d_single()` because it implies you can't use `plot_2d()` for a "single".
